name: build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Lint chapter files
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          rules: '/lint/rules/changelog.js'
          config: '/lint/config/changelog.yml'
          args: './CHANGELOG.md'

      - name: build
        run: | 
          make all
          echo ${{ github.sha }} > Release.txt

      - name: check if tagged
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "Add a tag to branch before merging"
          exit 1

      - name: Release
        if: ${{ startsWith(github.ref, 'refs/heads/') && startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          files:
            ./book.epub
            Release.txt
